### ISSUE TITLE
请求新增分支 autoSolver-php

### ISSUE THREAD

**Issue by longhuan1999** [BugMaker888/sheep#14]
[longhuan1999/sheep/tree/autoSolver-php](https://github.com/longhuan1999/sheep/tree/autoSolver-php)
将 [NB-Dragon/SheepSolver](https://github.com/NB-Dragon/SheepSolver) 的自动求解算法加到了抓包过程中，并进行了简单的调整和优化

**Comment by wang1784594241** [comment]
@longhuan1999 兄弟，挂个PHP环境的安装教程，链接也行，百度的一堆，有点痛苦呀，也不知道装哪个版本

**Comment by anymine94** [comment]
> [longhuan1999/sheep/tree/autoSolver-php](https://github.com/longhuan1999/sheep/tree/autoSolver-php) 将 [NB-Dragon/SheepSolver](https://github.com/NB-Dragon/SheepSolver) 的自动求解算法加到了抓包过程中，并进行了简单的调整和优化

`from os.path import isfile
from mitmproxy import ctx
from autoSolve import auto_solve
import execjs
import json
import os
import _thread



seed = [3270836840, 3431855579, 3015956679, 1737139174]
js_code = open("shuffle.js", encoding="utf-8").read()
map_data_path = "./map_data.txt"
map_data_raw = "./map_raw.txt"

with open(map_data_raw, encoding="utf-8") as f:
    a = f.read()
    response = json.loads(a)
    print(response)
with open(map_data_path, "w") as x:
    x.write(json.dumps(response, indent=4))
    x.close()


print("==========================================")
`

您好，我把[autoSolver-php]项目sheep.py，的开头改成这样了，中间所有def都删了，结尾删了addons = [Sheep()]，然后运行就显示

`已将当前关卡数据保存到当前路径下 map_data.json 文件！

将使用配置文件 config.json 的配置求解！

建议同时在新的命令行终端分别同时运行以下命令：
python3 autoSolve.py -s reverse
python3 autoSolve.py -p 0
python3 autoSolve.py -s reverse -p 0

开始求解，请稍等180秒...`
没有开始求解，我需要怎么修改这个文件才能调用求解呢，因为我电脑mitmproxy抓不到小程序的包，所以只能本地导入map和seed数据，麻烦了

**Comment by longhuan1999** [comment]
@anymine94 我提交了个 commit ，希望能对你有所帮助。
[https://github.com/longhuan1999/sheep/blob/autoSolver-php/sheep_manual.py](https://github.com/longhuan1999/sheep/blob/autoSolver-php/sheep_manual.py)
