### ISSUE TITLE
请求添加电脑抓包小程序教程

### ISSUE THREAD

**Issue by anymine94** [BugMaker888/sheep#16]
我用mitmproxy抓电脑小程序，显示抓不到包，能否添加电脑抓包小程序教程，或者在文件下添加一个直接填写map_info_ex?matchType=3和xxx.txt文件的位置（因为用http dubbger可以抓到数据），谢谢了

**Comment by BugMaker888** [comment]
我试了windows小程序抓包没问题，电脑先安装证书

**Comment by anymine94** [comment]
您好，我装了证书以后，能抓到通过https的qq空间信息，但是羊了个羊还是抓不到，用fiddle抓包也是抓不到羊了个样的数据

**Comment by BugMaker888** [comment]
电脑要设置6666端口作为代理

**Comment by anymine94** [comment]
我在电脑-设置-网络和internet-代理-手动设置代理填写了“127.0.0.1:6666”,微信登陆页面设置代理“127.0.0.1:6666”，以及通过“http://mitm.it/”下载“mitmproxy-ca-cert.p12”安装证书到受信任的根证书颁布机构，还是一样，不能抓到小程序包，微信版本是3.7.6.44，能不能指导我通过修改sheep文件，本地生成地图文件呢，我已经通过http dubbger抓到了map_info_ex?matchType=3和xxx.txt的centent数据

**Comment by BugMaker888** [comment]
微信登录页面不用设代理，设电脑的就行。
本地生成数据可以参考shepp.py，在make_map_data()方法里读取数据。

**Comment by anymine94** [comment]
谢谢了，已经修改完成了，麻烦了

**Comment by BugMaker888** [comment]
不客气

**Comment by lon91ong** [comment]
最后还是没有搞清楚mitmproxy抓包小程序的设置问题

**Comment by anymine94** [comment]
> 最后还是没有搞清楚mitmproxy抓包小程序的设置问题

mitmproxy抓包这个问题，我因为试过两三软件抓小程序包，然后电脑可能是微信版本的问题（win11+微信3.7.6.44)，导致抓不了或者直接加载不出来，有的说把小程序运行那个文件删了，再装就可以，但是测试下来都不行，唯一简单得处理方式就是用http dubbger抓包，只需要把软件和微信打开就能抓到，我后面修改是直接读取本地的map_date文件和修改seed[]

**Comment by lon91ong** [comment]
> > 最后还是没有搞清楚mitmproxy抓包小程序的设置问题
> 
> mitmproxy抓包这个问题...用http dubbger抓包，只需要把软件和微信打开就能抓到，我后面修改是直接读取本地的map_date文件和修改seed[]

小程序抓包[问题参考](https://blog.csdn.net/weixin_46552558/article/details/124037807), 修改WMPFRuntime文件夹只读并拒绝写入之后, 退回3.7.1版本小程序可以正常运行, 之后用mitmproxy做系统代理, 可以成功抓包.

好奇用http debugger手动抓包之后的操作, 希望分享一二.

**Comment by anymine94** [comment]
> 

seed = [3270836840, 3431855579, 3015956679, 1737139174]
js_code = open("shuffle.js", encoding="utf-8").read()
map_data_path = "./map_data.txt"
map_data_raw = "./map_raw.txt"

with open(map_data_raw, encoding="utf-8") as f:
    a = f.read()
    response = json.loads(a)
    print(response)
with open(map_data_path, "w") as x:
    x.write(json.dumps(response, indent=4))
    x.close()
把sheep.py开头像这个改一下，然后def的那些函数定义改一下就可以了

**Comment by BugMaker888** [comment]
电脑版小程序抓包教程：https://www.bilibili.com/video/BV1mt4y1u7ea/
