### ISSUE TITLE
进不去游戏

### ISSUE THREAD

**Issue by esome-zz** [BugMaker888/sheep#27]
都按照流程装好了，显示一切正常，但是手机小程序羊了个羊进不去，其他小程序都能打开，这是咋回事。电脑版小程序也能打开

**Comment by esome-zz** [comment]
4、使用
因为关卡数据每天只会请求一次，所以可以先删除游戏再重新进入。

手机进入游戏后，电脑刷新网页，就可以看到最新的游戏3d地图了。



卡在这里，手机没法进入游戏

**Comment by BugMaker888** [comment]
手机证书没配置好

**Comment by esome-zz** [comment]
> 手机证书没配置好

谢谢，可是我已经按照流程，下载了证书，使用的是安卓鸿蒙系统，按照网上流程在加密凭证里面把证书添加到信任，是否还有其他方法呢？

**Comment by BugMaker888** [comment]
改用安卓模拟器吧，不然安卓手机需要root的

**Comment by esome-zz** [comment]
> 改用安卓模拟器吧，不然安卓手机需要root的

好的，Thanks~~
