### ISSUE TITLE
可否建个电报群，每天只要有人跑出结果，把序列文件分享群里

### ISSUE THREAD

**Issue by lon91ong** [BugMaker888/sheep#29]
如题，现在的难点在于计算抓包环境搭建和跑计算结果，是否能跳过难点步骤，直接分享结果呢？

**Comment by BugMaker888** [comment]
目前php分支跑有解的话会把结果上传到服务器，可以通过网址 [https://ylgy.endless084.top/sheep_map/?id=735](https://ylgy.endless084.top/sheep_map/?id=735) 访问，修改id的值可以看到新的地图，查看网页源码可以看到`map_data`的值。

**Comment by lon91ong** [comment]
> 目前php分支有解的话会把结果上传到服务器，可以通过网址 https://ylgy.endless084.top/sheep_map/?id=735 访问，修改id的值可以看到新的地图，查看网页源码可以看到`map_data`的值。

id值有什么规律呢？按日期递增？

**Comment by BugMaker888** [comment]
把数值改大一点

**Comment by Fireky1in** [comment]
今日id 848开始到871

**Comment by Fireky1in** [comment]
> 把数值改大一点

咱们建个TG群吧

**Comment by Fireky1in** [comment]
https://t.me/yanglegeyangsuanfa
