### ISSUE TITLE
关于数据输入的优化思路

### ISSUE THREAD

**Issue by NB-Dragon** [BugMaker888/sheep#34]
关于抓包程序生成的map_data.js，我认为应该进行以下优化：
1: 只存放抓包回来的数据，不应该写成js文件，也就是存为json文件。
2: 网页上面通过交互的方式，读取本地数据文件，完成页面卡牌的更新。
3: 取消json文件中的layer数据，通过读取json文件重新生成。
4: 导出的json文件默认添加operations的空数组，便于用户粘贴答案。

**Comment by BugMaker888** [comment]
已修改
