### ISSUE TITLE
解析地图数据出错

### ISSUE THREAD

**Issue by esome-zz** [BugMaker888/sheep#35]
用[NB-Dragon](https://github.com/NB-Dragon) [SheepSolver](https://github.com/NB-Dragon/SheepSolver)
的跑出结果；
把map_data.json里面数据替换成当天的地图，同时添加上 "operations": [ ]数据
结果就是不加operations可以正常显示地图，加上以后就报错

**Comment by BugMaker888** [comment]
报了什么错

**Comment by esome-zz** [comment]
> 报了什么错
就是显示解析地图数据出错
![image](https://user-images.githubusercontent.com/12118134/203189770-3e046f9b-5c2f-4335-9fce-3027c9901216.png)

**Comment by esome-zz** [comment]
这是mapdata数据，不知道怎么回事。
[map_data.zip](https://github.com/BugMaker888/sheep/files/10061714/map_data.zip)

**Comment by esome-zz** [comment]
已经解决，谢位置放的不对，谢谢
