### ISSUE TITLE
求解

### ISSUE THREAD

**Issue by f13098804603** [BugMaker888/sheep#6]
今天的地图自动求不了解

**Comment by longhuan1999** [comment]
看代码，目前只是在3D地图上添加了根据`map_data.js`中JSON数据的`oprations`字段显示求解步骤的功能，目前`oprations`字段只有演示的`map_data.js`中有。抓包脚本`sheep.py`中还没有添加自动求解功能，也就没有往新获取的关卡地图数据中添加`oprations`字段

**Comment by BugMaker888** [comment]
目前还没有加入求解的算法

**Comment by f13098804603** [comment]
> 目前还没有加入求解的算法

大哥 加油 我看B站有个up 用你的3D地图 完善了算法

**Comment by BugMaker888** [comment]
> 

是的，我看到了

**Comment by longhuan1999** [comment]
> > 目前还没有加入求解的算法
> 
> 大哥 加油 我看B站有个up 用你的3D地图 完善了算法
是这个视频：[《羊了个羊》全网首个不用道具不用复活正常通关的解决方案]( https://www.bilibili.com/video/BV1GT411P7nx?share_source=copy_web&vd_source=2297b19bcb0baa6d97534d0312bd2d71) 吗？
我试了试他今天公开的源码：[NB-Dragon/SheepSolver](https://github.com/NB-Dragon/SheepSolver) ，5分钟内求解成功率暂时不高。
我也整合到了新的php分支：[longhuan1999/sheep](https://github.com/longhuan1999/sheep/tree/autoSolver-php)
