### ISSUE TITLE
打乱后的地图数据能拿到后再生成3D图吗

### ISSUE THREAD

**Issue by xu51150jie** [BugMaker888/sheep#8]
打乱后的地图数据能拿到后再生成3D图吗

**Comment by BugMaker888** [comment]
目前就是这样做的

**Comment by xu51150jie** [comment]
> 目前就是这样做的

我指的是使用随机道具后，再生成地图数据

**Comment by BugMaker888** [comment]
我知道打乱的实现方法，但是如果要重新显示打乱结果的话，就需要把打乱的算法放在html里，要改很多代码。

**Comment by xu51150jie** [comment]
> 我知道打乱的实现方法，但是如果要重新显示打乱结果的话，就需要把打乱的算法放在html里，要改很多代码。

请问一下，打乱实现方法能分享一下吗
